os: osx
osx_image: xcode11.1
language: swift
xcode_destination: platform=iOS Simulator,OS=11.2,name=iPhone X
warnings_are_errors: false

cache:
  directories:
  - Carthage
  - Firebase

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage

before_script:
  - sh ./scripts/firebase.sh
  - sh ./scripts/intelligent-bootstrap.sh

script: xcodebuild clean build test -project iOS-Email-Client.xcodeproj -destination 'platform=iOS Simulator,name=iPhone X,OS=11.2' -scheme iOS-Email-Client -sdk iphonesimulator -quiet ONLY_ACTIVE_ARCH=NO

notifications:
  email: false