os: osx
osx_image: xcode10.2
language: swift
warnings_are_errors: false

cache:
  directories:
  - Carthage
  - Firebase

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage

before_script:
  - sh ./scripts/intelligent-bootstrap.sh
  - sh ./scripts/firebase.sh

script: xcodebuild clean build test -project iOS-Email-Client.xcodeproj -scheme iOS-Email-Client -sdk iphonesimulator -quiet ONLY_ACTIVE_ARCH=NO

notifications:
  email: false